eureka:
 client:
   serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     
server:
  port: 7777
  
spring:
     datasource: 
        url: jdbc:mysql://dvhtest.ctgr6wvwj3bk.us-west-2.rds.amazonaws.com:3306/dvh_di 
        username: sedwards 
        password: password123
        driver-class-name: com.mysql.jdbc.Driver
        test-on-borrow: true
        validation-query: SELECT 1
     jpa: 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate:
             ddl-auto: update
          
     
          
         
         
         

 
    
    
